using System.Text.Json;
using Xunit;

namespace Verifiabl.Tests;

/// <summary>
/// Cross-SDK parity: the fixtures were generated by the Verifiabl Node.js SDK
/// (verifiabl-node) renderer for the same inputs. The two SDKs must emit the
/// same badge for the same record so documents look identical regardless of the
/// provider's stack.
/// </summary>
public class NodeSdkParityTests
{
    private const string Reference = "u0FE9WLIS7GYKQnpJPygBw";

    private static string Ciphertext()
    {
        return string.Concat(Enumerable.Repeat("Ab3", 80)) + "Zz19-_";
    }

    private static string Fixture(string name)
    {
        return File.ReadAllText(Path.Combine(AppContext.BaseDirectory, "Fixtures", name));
    }

    [Fact]
    public void MatchesTheNodeRendererForTheDefaultBadge()
    {
        BarcodeSvgResult result = VerifiablBarcode.CreateSvg(
            new BarcodeParts(Reference, Ciphertext()));

        using JsonDocument meta = JsonDocument.Parse(Fixture("node-svg-meta.json"));
        JsonElement expected = meta.RootElement.GetProperty("default-480");

        Assert.Equal(expected.GetProperty("content").GetString(), result.Content);
        Assert.Equal(expected.GetProperty("width").GetDouble(), result.Width);
        Assert.Equal(expected.GetProperty("height").GetDouble(), result.Height);
        Assert.Equal("M", ToNodeLevel(result.ErrorCorrectionLevel));
        Assert.Equal(expected.GetProperty("modulePx").GetDouble(), result.ModulePx);
        Assert.Equal(expected.GetProperty("degraded").GetBoolean(), result.Degraded);
        Assert.Equal(Fixture("node-svg-default-480.svg"), result.Svg);
    }

    [Fact]
    public void MatchesTheNodeRendererForASandboxQuartileBadge()
    {
        BarcodeSvgResult result = VerifiablBarcode.CreateSvg(
            new BarcodeParts(Reference, Ciphertext()),
            new BarcodeSvgOptions
            {
                Environment = VerifiablEnvironment.Sandbox,
                MaxErrorCorrection = BarcodeErrorCorrectionLevel.Quartile,
                Width = 720,
            });

        using JsonDocument meta = JsonDocument.Parse(Fixture("node-svg-meta.json"));
        JsonElement expected = meta.RootElement.GetProperty("sandbox-q-720");

        Assert.Equal(expected.GetProperty("content").GetString(), result.Content);
        Assert.Equal("Q", ToNodeLevel(result.ErrorCorrectionLevel));
        Assert.Equal(expected.GetProperty("modulePx").GetDouble(), result.ModulePx);
        Assert.Equal(Fixture("node-svg-sandbox-q-720.svg"), result.Svg);
    }

    private static string ToNodeLevel(BarcodeErrorCorrectionLevel level) => level switch
    {
        BarcodeErrorCorrectionLevel.Quartile => "Q",
        BarcodeErrorCorrectionLevel.Medium => "M",
        _ => "L",
    };
}
