using System.Text.Json;
using Xunit;

namespace Verifiabl.Tests;

/// <summary>
/// Cross-SDK parity: the fixtures were generated by the Verifiabl Node.js SDK
/// (verifiabl-node) renderer for the same inputs. The two SDKs must emit the
/// same badge for the same record so documents look identical regardless of the
/// provider's stack.
/// </summary>
public class NodeSdkParityTests
{
    private const string Reference = "u0FE9WLIS7GYKQnpJPygBw";

    private static string Ciphertext()
    {
        return string.Concat(Enumerable.Repeat("Ab3", 80)) + "Zz19-_";
    }

    private static string Fixture(string name)
    {
        return File.ReadAllText(Path.Combine(AppContext.BaseDirectory, "Fixtures", name));
    }

    [Fact]
    public void MatchesTheNodeRendererForTheDefaultBadge()
    {
        BarcodeSvgResult result = VerifiablBarcode.CreateSvg(
            new BarcodeParts(Reference, Ciphertext()));

        using JsonDocument meta = JsonDocument.Parse(Fixture("node-svg-meta.json"));
        JsonElement expected = meta.RootElement.GetProperty("default-480");

        Assert.Equal(expected.GetProperty("content").GetString(), result.Content);
        Assert.Equal(expected.GetProperty("width").GetDouble(), result.Width);
        Assert.Equal(expected.GetProperty("height").GetDouble(), result.Height);
        Assert.Equal("M", ToNodeLevel(result.ErrorCorrectionLevel));
        Assert.Equal(expected.GetProperty("modulePx").GetDouble(), result.ModulePx);
        Assert.Equal(expected.GetProperty("degraded").GetBoolean(), result.Degraded);
        Assert.Equal(Fixture("node-svg-default-480.svg"), result.Svg);
    }

    [Fact]
    public void MatchesTheNodeRendererForASandboxQuartileBadge()
    {
        BarcodeSvgResult result = VerifiablBarcode.CreateSvg(
            new BarcodeParts(Reference, Ciphertext()),
            new BarcodeSvgOptions
            {
                Environment = VerifiablEnvironment.Sandbox,
                MaxErrorCorrection = BarcodeErrorCorrectionLevel.Quartile,
                Width = 720,
            });

        using JsonDocument meta = JsonDocument.Parse(Fixture("node-svg-meta.json"));
        JsonElement expected = meta.RootElement.GetProperty("sandbox-q-720");

        Assert.Equal(expected.GetProperty("content").GetString(), result.Content);
        Assert.Equal("Q", ToNodeLevel(result.ErrorCorrectionLevel));
        Assert.Equal(expected.GetProperty("modulePx").GetDouble(), result.ModulePx);
        Assert.Equal(Fixture("node-svg-sandbox-q-720.svg"), result.Svg);
    }

    /// <summary>
    /// PNG parity is raster parity: the fixtures are the exact RGBA pixels the
    /// Node compositor produced (PNG file bytes differ across SDKs because the
    /// DEFLATE encoders differ). The Node test suite decodes these same rasters
    /// with an independent QR reader, so byte equality here is also the
    /// scannability proof.
    /// </summary>
    [Theory]
    [InlineData("png-default-1440", 1440, false, false, false)]
    [InlineData("png-default-720", 720, false, false, false)]
    [InlineData("png-sandbox-q-480", 480, true, true, false)]
    [InlineData("png-v2-mixed-mode-720", 720, false, false, true)]
    public void PngRasterMatchesTheNodeCompositor(
        string caseName,
        int pixelWidth,
        bool sandbox,
        bool quartile,
        bool v2)
    {
        var options = new BarcodeSvgOptions
        {
            Format = v2 ? BarcodePayloadFormat.V2 : BarcodePayloadFormat.V1,
            Environment = sandbox ? VerifiablEnvironment.Sandbox : VerifiablEnvironment.Production,
            MaxErrorCorrection = quartile
                ? BarcodeErrorCorrectionLevel.Quartile
                : BarcodeErrorCorrectionLevel.Medium,
        };
        string ciphertext = v2 ? Ciphertext().Substring(0, Ciphertext().Length - 1) + "w" : Ciphertext();
        Internal.PngBadgeRenderer.CompositedBadge badge = Internal.PngBadgeRenderer.Compose(
            new BarcodeParts(Reference, ciphertext),
            options,
            pixelWidth);

        using JsonDocument meta = JsonDocument.Parse(Fixture("node-png-meta.json"));
        JsonElement expected = meta.RootElement.GetProperty(caseName);
        Assert.Equal(expected.GetProperty("content").GetString(), badge.Content);
        Assert.Equal(expected.GetProperty("width").GetInt32(), badge.Width);
        Assert.Equal(expected.GetProperty("height").GetInt32(), badge.Height);
        Assert.Equal(
            expected.GetProperty("errorCorrectionLevel").GetString(),
            ToNodeLevel(badge.ErrorCorrectionLevel));
        Assert.Equal(expected.GetProperty("qrVersion").GetInt32(), badge.QrVersion);
        Assert.Equal(expected.GetProperty("modulePx").GetDouble(), badge.ModulePx);
        Assert.Equal(expected.GetProperty("degraded").GetBoolean(), badge.Degraded);

        byte[] nodeRaster = InflateFixture($"node-{caseName}.rgba.deflate");
        AssertRastersEqual(nodeRaster, badge.Rgba, badge.Width);
    }

    private static byte[] InflateFixture(string name)
    {
        byte[] deflated = File.ReadAllBytes(Path.Combine(AppContext.BaseDirectory, "Fixtures", name));
        using var inflate = new System.IO.Compression.DeflateStream(
            new MemoryStream(deflated, writable: false),
            System.IO.Compression.CompressionMode.Decompress);
        using var buffer = new MemoryStream();
        inflate.CopyTo(buffer);
        return buffer.ToArray();
    }

    private static void AssertRastersEqual(byte[] expected, byte[] actual, int width)
    {
        Assert.Equal(expected.Length, actual.Length);
        for (int i = 0; i < expected.Length; i++)
        {
            if (expected[i] != actual[i])
            {
                int pixel = i / 4;
                Assert.Fail(
                    $"raster differs at byte {i} (pixel {pixel % width},{pixel / width}, "
                    + $"channel {i % 4}): expected {expected[i]}, got {actual[i]}");
            }
        }
    }

    private static string ToNodeLevel(BarcodeErrorCorrectionLevel level) => level switch
    {
        BarcodeErrorCorrectionLevel.Quartile => "Q",
        BarcodeErrorCorrectionLevel.Medium => "M",
        _ => "L",
    };
}
