// <auto-generated> Generated from ecosystems/node/src/payslipV2.ts; do not edit. </auto-generated>
#nullable enable
using System.Collections.ObjectModel;

namespace Verifiabl.Client;

/// <summary>Earnings line <c>type</c> values for <c>au.payslip.v2</c>.</summary>
public static class AustralianEarningsTypes
{
    /// <summary>The <c>paid_leave</c> code.</summary>
    public const string PaidLeave = "paid_leave";

    /// <summary>The <c>allowance</c> code.</summary>
    public const string Allowance = "allowance";

    /// <summary>The <c>ordinary</c> code.</summary>
    public const string Ordinary = "ordinary";

    /// <summary>The <c>overtime</c> code.</summary>
    public const string Overtime = "overtime";

    /// <summary>The <c>bonus_commission</c> code.</summary>
    public const string BonusCommission = "bonus_commission";

    /// <summary>The <c>directors_fees</c> code.</summary>
    public const string DirectorsFees = "directors_fees";

    /// <summary>The <c>lump_sum</c> code.</summary>
    public const string LumpSum = "lump_sum";

    /// <summary>The <c>return_to_work</c> code.</summary>
    public const string ReturnToWork = "return_to_work";

    /// <summary>Every accepted value, in contract order.</summary>
    public static readonly IReadOnlyList<string> All = new ReadOnlyCollection<string>(
    [
        PaidLeave,
        Allowance,
        Ordinary,
        Overtime,
        BonusCommission,
        DirectorsFees,
        LumpSum,
        ReturnToWork,
    ]);
}

/// <summary>Paid leave <c>leave_type</c> values for <c>au.payslip.v2</c>.</summary>
public static class AustralianPaidLeaveTypes
{
    /// <summary>The <c>cash_out_in_service</c> code.</summary>
    public const string CashOutInService = "cash_out_in_service";

    /// <summary>The <c>unused_on_termination</c> code.</summary>
    public const string UnusedOnTermination = "unused_on_termination";

    /// <summary>The <c>paid_parental</c> code.</summary>
    public const string PaidParental = "paid_parental";

    /// <summary>The <c>workers_compensation</c> code.</summary>
    public const string WorkersCompensation = "workers_compensation";

    /// <summary>The <c>ancillary_defence</c> code.</summary>
    public const string AncillaryDefence = "ancillary_defence";

    /// <summary>The <c>other_paid_leave</c> code.</summary>
    public const string OtherPaidLeave = "other_paid_leave";

    /// <summary>Every accepted value, in contract order.</summary>
    public static readonly IReadOnlyList<string> All = new ReadOnlyCollection<string>(
    [
        CashOutInService,
        UnusedOnTermination,
        PaidParental,
        WorkersCompensation,
        AncillaryDefence,
        OtherPaidLeave,
    ]);
}

/// <summary>Allowance <c>allowance_type</c> values for <c>au.payslip.v2</c>.</summary>
public static class AustralianAllowanceTypes
{
    /// <summary>The <c>cents_per_km</c> code.</summary>
    public const string CentsPerKm = "cents_per_km";

    /// <summary>The <c>award_transport</c> code.</summary>
    public const string AwardTransport = "award_transport";

    /// <summary>The <c>laundry</c> code.</summary>
    public const string Laundry = "laundry";

    /// <summary>The <c>overtime_meal</c> code.</summary>
    public const string OvertimeMeal = "overtime_meal";

    /// <summary>The <c>travel</c> code.</summary>
    public const string Travel = "travel";

    /// <summary>The <c>tools</c> code.</summary>
    public const string Tools = "tools";

    /// <summary>The <c>tasks</c> code.</summary>
    public const string Tasks = "tasks";

    /// <summary>The <c>qualifications</c> code.</summary>
    public const string Qualifications = "qualifications";

    /// <summary>The <c>other</c> code.</summary>
    public const string Other = "other";

    /// <summary>Every accepted value, in contract order.</summary>
    public static readonly IReadOnlyList<string> All = new ReadOnlyCollection<string>(
    [
        CentsPerKm,
        AwardTransport,
        Laundry,
        OvertimeMeal,
        Travel,
        Tools,
        Tasks,
        Qualifications,
        Other,
    ]);
}

/// <summary><c>other_category</c> values for an <c>other</c> allowance in <c>au.payslip.v2</c>.</summary>
public static class AustralianOtherAllowanceCategories
{
    /// <summary>The <c>home_office</c> code.</summary>
    public const string HomeOffice = "home_office";

    /// <summary>The <c>non_deductible</c> code.</summary>
    public const string NonDeductible = "non_deductible";

    /// <summary>The <c>transport_fares</c> code.</summary>
    public const string TransportFares = "transport_fares";

    /// <summary>The <c>uniform</c> code.</summary>
    public const string Uniform = "uniform";

    /// <summary>The <c>private_vehicle</c> code.</summary>
    public const string PrivateVehicle = "private_vehicle";

    /// <summary>The <c>general</c> code.</summary>
    public const string General = "general";

    /// <summary>Every accepted value, in contract order.</summary>
    public static readonly IReadOnlyList<string> All = new ReadOnlyCollection<string>(
    [
        HomeOffice,
        NonDeductible,
        TransportFares,
        Uniform,
        PrivateVehicle,
        General,
    ]);
}

/// <summary>Salary sacrifice <c>type</c> values for <c>au.payslip.v2</c>.</summary>
public static class AustralianSalarySacrificeTypes
{
    /// <summary>The <c>super</c> code.</summary>
    public const string Super = "super";

    /// <summary>The <c>other</c> code.</summary>
    public const string Other = "other";

    /// <summary>Every accepted value, in contract order.</summary>
    public static readonly IReadOnlyList<string> All = new ReadOnlyCollection<string>(
    [
        Super,
        Other,
    ]);
}

/// <summary>Deduction <c>type</c> values for <c>au.payslip.v2</c>.</summary>
public static class AustralianDeductionTypes
{
    /// <summary>The <c>union_professional_fees</c> code.</summary>
    public const string UnionProfessionalFees = "union_professional_fees";

    /// <summary>The <c>workplace_giving</c> code.</summary>
    public const string WorkplaceGiving = "workplace_giving";

    /// <summary>The <c>child_support_deduction</c> code.</summary>
    public const string ChildSupportDeduction = "child_support_deduction";

    /// <summary>The <c>child_support_garnishee</c> code.</summary>
    public const string ChildSupportGarnishee = "child_support_garnishee";

    /// <summary>The <c>other_post_tax</c> code.</summary>
    public const string OtherPostTax = "other_post_tax";

    /// <summary>Every accepted value, in contract order.</summary>
    public static readonly IReadOnlyList<string> All = new ReadOnlyCollection<string>(
    [
        UnionProfessionalFees,
        WorkplaceGiving,
        ChildSupportDeduction,
        ChildSupportGarnishee,
        OtherPostTax,
    ]);
}

/// <summary>Superannuation <c>contribution_type</c> values for <c>au.payslip.v2</c>.</summary>
public static class AustralianSuperContributionTypes
{
    /// <summary>The <c>superannuation_guarantee</c> code.</summary>
    public const string SuperannuationGuarantee = "superannuation_guarantee";

    /// <summary>The <c>resc</c> code.</summary>
    public const string Resc = "resc";

    /// <summary>The <c>salary_sacrifice</c> code.</summary>
    public const string SalarySacrifice = "salary_sacrifice";

    /// <summary>Every accepted value, in contract order.</summary>
    public static readonly IReadOnlyList<string> All = new ReadOnlyCollection<string>(
    [
        SuperannuationGuarantee,
        Resc,
        SalarySacrifice,
    ]);
}

/// <summary><c>pay_frequency</c> values for <c>au.payslip.v2</c>.</summary>
public static class AustralianPayFrequencies
{
    /// <summary>The <c>weekly</c> code.</summary>
    public const string Weekly = "weekly";

    /// <summary>The <c>fortnightly</c> code.</summary>
    public const string Fortnightly = "fortnightly";

    /// <summary>The <c>monthly</c> code.</summary>
    public const string Monthly = "monthly";

    /// <summary>The <c>quarterly</c> code.</summary>
    public const string Quarterly = "quarterly";

    /// <summary>The <c>four_weekly</c> code.</summary>
    public const string FourWeekly = "four_weekly";

    /// <summary>The <c>semi_monthly</c> code.</summary>
    public const string SemiMonthly = "semi_monthly";

    /// <summary>Every accepted value, in contract order.</summary>
    public static readonly IReadOnlyList<string> All = new ReadOnlyCollection<string>(
    [
        Weekly,
        Fortnightly,
        Monthly,
        Quarterly,
        FourWeekly,
        SemiMonthly,
    ]);
}

/// <summary><c>employment_basis</c> values for <c>au.payslip.v2</c>.</summary>
public static class AustralianEmploymentBases
{
    /// <summary>The <c>full_time</c> code.</summary>
    public const string FullTime = "full_time";

    /// <summary>The <c>part_time</c> code.</summary>
    public const string PartTime = "part_time";

    /// <summary>The <c>casual</c> code.</summary>
    public const string Casual = "casual";

    /// <summary>The <c>labour_hire</c> code.</summary>
    public const string LabourHire = "labour_hire";

    /// <summary>The <c>voluntary_agreement</c> code.</summary>
    public const string VoluntaryAgreement = "voluntary_agreement";

    /// <summary>The <c>death_beneficiary</c> code.</summary>
    public const string DeathBeneficiary = "death_beneficiary";

    /// <summary>The <c>non_employee</c> code.</summary>
    public const string NonEmployee = "non_employee";

    /// <summary>Every accepted value, in contract order.</summary>
    public static readonly IReadOnlyList<string> All = new ReadOnlyCollection<string>(
    [
        FullTime,
        PartTime,
        Casual,
        LabourHire,
        VoluntaryAgreement,
        DeathBeneficiary,
        NonEmployee,
    ]);
}

/// <summary><c>engagement_type</c> values for <c>au.payslip.v2</c>.</summary>
public static class AustralianEngagementTypes
{
    /// <summary>The <c>permanent</c> code.</summary>
    public const string Permanent = "permanent";

    /// <summary>The <c>fixed_term</c> code.</summary>
    public const string FixedTerm = "fixed_term";

    /// <summary>Every accepted value, in contract order.</summary>
    public static readonly IReadOnlyList<string> All = new ReadOnlyCollection<string>(
    [
        Permanent,
        FixedTerm,
    ]);
}

/// <summary>Earnings line <c>type</c> values for <c>nz.payslip.v2</c>.</summary>
public static class NewZealandEarningsTypes
{
    /// <summary>The <c>paid_leave</c> code.</summary>
    public const string PaidLeave = "paid_leave";

    /// <summary>The <c>allowance</c> code.</summary>
    public const string Allowance = "allowance";

    /// <summary>The <c>ordinary</c> code.</summary>
    public const string Ordinary = "ordinary";

    /// <summary>The <c>overtime</c> code.</summary>
    public const string Overtime = "overtime";

    /// <summary>The <c>penal_rate</c> code.</summary>
    public const string PenalRate = "penal_rate";

    /// <summary>The <c>piece_work</c> code.</summary>
    public const string PieceWork = "piece_work";

    /// <summary>The <c>bonus_commission</c> code.</summary>
    public const string BonusCommission = "bonus_commission";

    /// <summary>The <c>extra_pay</c> code.</summary>
    public const string ExtraPay = "extra_pay";

    /// <summary>The <c>schedular_payment</c> code.</summary>
    public const string SchedularPayment = "schedular_payment";

    /// <summary>The <c>directors_fees</c> code.</summary>
    public const string DirectorsFees = "directors_fees";

    /// <summary>The <c>pay_as_you_go_holiday_pay</c> code.</summary>
    public const string PayAsYouGoHolidayPay = "pay_as_you_go_holiday_pay";

    /// <summary>The <c>leave_compensation_payment</c> code.</summary>
    public const string LeaveCompensationPayment = "leave_compensation_payment";

    /// <summary>The <c>annual_holiday_cash_out</c> code.</summary>
    public const string AnnualHolidayCashOut = "annual_holiday_cash_out";

    /// <summary>The <c>alternative_holiday_cash_out</c> code.</summary>
    public const string AlternativeHolidayCashOut = "alternative_holiday_cash_out";

    /// <summary>The <c>holiday_pay_on_termination</c> code.</summary>
    public const string HolidayPayOnTermination = "holiday_pay_on_termination";

    /// <summary>Every accepted value, in contract order.</summary>
    public static readonly IReadOnlyList<string> All = new ReadOnlyCollection<string>(
    [
        PaidLeave,
        Allowance,
        Ordinary,
        Overtime,
        PenalRate,
        PieceWork,
        BonusCommission,
        ExtraPay,
        SchedularPayment,
        DirectorsFees,
        PayAsYouGoHolidayPay,
        LeaveCompensationPayment,
        AnnualHolidayCashOut,
        AlternativeHolidayCashOut,
        HolidayPayOnTermination,
    ]);
}

/// <summary>Paid leave <c>leave_type</c> values for <c>nz.payslip.v2</c>.</summary>
public static class NewZealandPaidLeaveTypes
{
    /// <summary>The <c>annual_holiday</c> code.</summary>
    public const string AnnualHoliday = "annual_holiday";

    /// <summary>The <c>public_holiday</c> code.</summary>
    public const string PublicHoliday = "public_holiday";

    /// <summary>The <c>alternative_holiday</c> code.</summary>
    public const string AlternativeHoliday = "alternative_holiday";

    /// <summary>The <c>sick_leave</c> code.</summary>
    public const string SickLeave = "sick_leave";

    /// <summary>The <c>bereavement_leave</c> code.</summary>
    public const string BereavementLeave = "bereavement_leave";

    /// <summary>The <c>other_paid_leave</c> code.</summary>
    public const string OtherPaidLeave = "other_paid_leave";

    /// <summary>Every accepted value, in contract order.</summary>
    public static readonly IReadOnlyList<string> All = new ReadOnlyCollection<string>(
    [
        AnnualHoliday,
        PublicHoliday,
        AlternativeHoliday,
        SickLeave,
        BereavementLeave,
        OtherPaidLeave,
    ]);
}

/// <summary>Allowance <c>allowance_type</c> values for <c>nz.payslip.v2</c>.</summary>
public static class NewZealandAllowanceTypes
{
    /// <summary>The <c>meal</c> code.</summary>
    public const string Meal = "meal";

    /// <summary>The <c>travel</c> code.</summary>
    public const string Travel = "travel";

    /// <summary>The <c>accommodation</c> code.</summary>
    public const string Accommodation = "accommodation";

    /// <summary>The <c>vehicle</c> code.</summary>
    public const string Vehicle = "vehicle";

    /// <summary>The <c>phone</c> code.</summary>
    public const string Phone = "phone";

    /// <summary>The <c>tools</c> code.</summary>
    public const string Tools = "tools";

    /// <summary>The <c>uniform</c> code.</summary>
    public const string Uniform = "uniform";

    /// <summary>The <c>on_call</c> code.</summary>
    public const string OnCall = "on_call";

    /// <summary>The <c>shift</c> code.</summary>
    public const string Shift = "shift";

    /// <summary>The <c>first_aid</c> code.</summary>
    public const string FirstAid = "first_aid";

    /// <summary>The <c>higher_duties</c> code.</summary>
    public const string HigherDuties = "higher_duties";

    /// <summary>The <c>qualification</c> code.</summary>
    public const string Qualification = "qualification";

    /// <summary>The <c>other</c> code.</summary>
    public const string Other = "other";

    /// <summary>Every accepted value, in contract order.</summary>
    public static readonly IReadOnlyList<string> All = new ReadOnlyCollection<string>(
    [
        Meal,
        Travel,
        Accommodation,
        Vehicle,
        Phone,
        Tools,
        Uniform,
        OnCall,
        Shift,
        FirstAid,
        HigherDuties,
        Qualification,
        Other,
    ]);
}

/// <summary>Deduction <c>type</c> values for <c>nz.payslip.v2</c>.</summary>
public static class NewZealandDeductionTypes
{
    /// <summary>The <c>union_fees</c> code.</summary>
    public const string UnionFees = "union_fees";

    /// <summary>The <c>payroll_donation</c> code.</summary>
    public const string PayrollDonation = "payroll_donation";

    /// <summary>The <c>attachment_order</c> code.</summary>
    public const string AttachmentOrder = "attachment_order";

    /// <summary>The <c>ir_arrears</c> code.</summary>
    public const string IrArrears = "ir_arrears";

    /// <summary>The <c>other_post_tax</c> code.</summary>
    public const string OtherPostTax = "other_post_tax";

    /// <summary>Every accepted value, in contract order.</summary>
    public static readonly IReadOnlyList<string> All = new ReadOnlyCollection<string>(
    [
        UnionFees,
        PayrollDonation,
        AttachmentOrder,
        IrArrears,
        OtherPostTax,
    ]);
}

/// <summary>Leave balance <c>unit</c> values for <c>nz.payslip.v2</c>.</summary>
public static class NewZealandLeaveBalanceUnits
{
    /// <summary>The <c>hours</c> code.</summary>
    public const string Hours = "hours";

    /// <summary>The <c>days</c> code.</summary>
    public const string Days = "days";

    /// <summary>The <c>weeks</c> code.</summary>
    public const string Weeks = "weeks";

    /// <summary>Every accepted value, in contract order.</summary>
    public static readonly IReadOnlyList<string> All = new ReadOnlyCollection<string>(
    [
        Hours,
        Days,
        Weeks,
    ]);
}
