// <auto-generated> Generated from ecosystems/node/src/payslipV2.ts; do not edit. </auto-generated>
#nullable enable
using System.Linq;

namespace Verifiabl.Client;

internal static class GeneratedPayslipCopies
{
    internal static AustralianPayslipV2Hourly Copy(AustralianPayslipV2Hourly source) => new()
    {
        OrdinaryRate = source.OrdinaryRate,
        Hours = source.Hours,
        Amount = source.Amount,
    };

    internal static AustralianPayslipV2EarningsItem Copy(AustralianPayslipV2EarningsItem source) => new()
    {
        Type = source.Type,
        LeaveType = source.LeaveType,
        Amount = source.Amount,
        Units = source.Units,
        Rate = source.Rate,
        YtdAmount = source.YtdAmount,
        AllowanceType = source.AllowanceType,
        OtherCategory = source.OtherCategory,
    };

    internal static AustralianPayslipV2SalarySacrificeItem Copy(AustralianPayslipV2SalarySacrificeItem source) => new()
    {
        Type = source.Type,
        Amount = source.Amount,
        YtdAmount = source.YtdAmount,
    };

    internal static AustralianPayslipV2DeductionsItem Copy(AustralianPayslipV2DeductionsItem source) => new()
    {
        Type = source.Type,
        Amount = source.Amount,
        YtdAmount = source.YtdAmount,
    };

    internal static AustralianPayslipV2SuperannuationItem Copy(AustralianPayslipV2SuperannuationItem source) => new()
    {
        ContributionType = source.ContributionType,
        Amount = source.Amount,
        Rate = source.Rate,
        YtdAmount = source.YtdAmount,
        Usi = source.Usi,
    };

    internal static AustralianPayslipV2Ytd Copy(AustralianPayslipV2Ytd source) => new()
    {
        Taxable = source.Taxable,
        Super = source.Super,
        NonTaxable = source.NonTaxable,
        PostTaxDeductions = source.PostTaxDeductions,
        Reimbursements = source.Reimbursements,
    };

    internal static AustralianPayslipV2 Copy(AustralianPayslipV2 source) => new()
    {
        PeriodStart = source.PeriodStart,
        PeriodEnd = source.PeriodEnd,
        PaymentDate = source.PaymentDate,
        Currency = source.Currency,
        Gross = source.Gross,
        Paygw = source.Paygw,
        Net = source.Net,
        YtdGross = source.YtdGross,
        YtdPaygw = source.YtdPaygw,
        PayFrequency = source.PayFrequency,
        EmploymentBasis = source.EmploymentBasis,
        EngagementType = source.EngagementType,
        Award = source.Award,
        Hourly = source.Hourly is null ? null : Copy(source.Hourly),
        AnnualRate = source.AnnualRate,
        TaxableGross = source.TaxableGross,
        StslWithholding = source.StslWithholding,
        Earnings = source.Earnings is null ? null : source.Earnings.Select(item => item is null ? null! : Copy(item)).ToList(),
        SalarySacrifice = source.SalarySacrifice is null ? null : source.SalarySacrifice.Select(item => item is null ? null! : Copy(item)).ToList(),
        Deductions = source.Deductions is null ? null : source.Deductions.Select(item => item is null ? null! : Copy(item)).ToList(),
        Superannuation = source.Superannuation is null ? null : source.Superannuation.Select(item => item is null ? null! : Copy(item)).ToList(),
        Reimbursements = source.Reimbursements,
        Ytd = source.Ytd is null ? null : Copy(source.Ytd),
    };

    internal static NewZealandPayslipV2Hourly Copy(NewZealandPayslipV2Hourly source) => new()
    {
        OrdinaryRate = source.OrdinaryRate,
        Hours = source.Hours,
        Amount = source.Amount,
    };

    internal static NewZealandPayslipV2EarningsItem Copy(NewZealandPayslipV2EarningsItem source) => new()
    {
        Type = source.Type,
        LeaveType = source.LeaveType,
        Amount = source.Amount,
        Units = source.Units,
        Rate = source.Rate,
        YtdAmount = source.YtdAmount,
        AllowanceType = source.AllowanceType,
    };

    internal static NewZealandPayslipV2DeductionsItem Copy(NewZealandPayslipV2DeductionsItem source) => new()
    {
        Type = source.Type,
        Amount = source.Amount,
        YtdAmount = source.YtdAmount,
    };

    internal static NewZealandPayslipV2LeaveBalancesAnnual Copy(NewZealandPayslipV2LeaveBalancesAnnual source) => new()
    {
        Amount = source.Amount,
        Unit = source.Unit,
    };

    internal static NewZealandPayslipV2LeaveBalancesAnnualAccruedThisPeriod Copy(NewZealandPayslipV2LeaveBalancesAnnualAccruedThisPeriod source) => new()
    {
        Amount = source.Amount,
        Unit = source.Unit,
    };

    internal static NewZealandPayslipV2LeaveBalancesSick Copy(NewZealandPayslipV2LeaveBalancesSick source) => new()
    {
        Amount = source.Amount,
        Unit = source.Unit,
    };

    internal static NewZealandPayslipV2LeaveBalancesSickAccruedThisPeriod Copy(NewZealandPayslipV2LeaveBalancesSickAccruedThisPeriod source) => new()
    {
        Amount = source.Amount,
        Unit = source.Unit,
    };

    internal static NewZealandPayslipV2LeaveBalancesAlternative Copy(NewZealandPayslipV2LeaveBalancesAlternative source) => new()
    {
        Amount = source.Amount,
        Unit = source.Unit,
    };

    internal static NewZealandPayslipV2LeaveBalances Copy(NewZealandPayslipV2LeaveBalances source) => new()
    {
        Annual = source.Annual is null ? null : Copy(source.Annual),
        AnnualAccruedThisPeriod = source.AnnualAccruedThisPeriod is null ? null : Copy(source.AnnualAccruedThisPeriod),
        Sick = source.Sick is null ? null : Copy(source.Sick),
        SickAccruedThisPeriod = source.SickAccruedThisPeriod is null ? null : Copy(source.SickAccruedThisPeriod),
        Alternative = source.Alternative is null ? null : Copy(source.Alternative),
    };

    internal static NewZealandPayslipV2Ytd Copy(NewZealandPayslipV2Ytd source) => new()
    {
        StudentLoan = source.StudentLoan,
        KiwisaverEmployee = source.KiwisaverEmployee,
        KiwisaverEmployer = source.KiwisaverEmployer,
        ChildSupport = source.ChildSupport,
        NonTaxable = source.NonTaxable,
        PostTaxDeductions = source.PostTaxDeductions,
        Reimbursements = source.Reimbursements,
    };

    internal static NewZealandPayslipV2 Copy(NewZealandPayslipV2 source) => new()
    {
        PeriodStart = source.PeriodStart,
        PeriodEnd = source.PeriodEnd,
        PaymentDate = source.PaymentDate,
        Currency = source.Currency,
        Gross = source.Gross,
        Paye = source.Paye,
        Net = source.Net,
        YtdGross = source.YtdGross,
        YtdPaye = source.YtdPaye,
        PayCycle = source.PayCycle,
        TaxCode = source.TaxCode,
        EmploymentType = source.EmploymentType,
        HoursPaid = source.HoursPaid,
        Hourly = source.Hourly is null ? null : Copy(source.Hourly),
        AnnualRate = source.AnnualRate,
        EarningsNotLiableForAcc = source.EarningsNotLiableForAcc,
        Earnings = source.Earnings is null ? null : source.Earnings.Select(item => item is null ? null! : Copy(item)).ToList(),
        EmployeeShareScheme = source.EmployeeShareScheme,
        PriorPeriodGrossAdjustment = source.PriorPeriodGrossAdjustment,
        PriorPeriodPayeAdjustment = source.PriorPeriodPayeAdjustment,
        PayrollDonationTaxCredit = source.PayrollDonationTaxCredit,
        StudentLoan = source.StudentLoan,
        Slcir = source.Slcir,
        Slbor = source.Slbor,
        ChildSupport = source.ChildSupport,
        KiwisaverEmployeeDeduction = source.KiwisaverEmployeeDeduction,
        KiwisaverEmployeeRate = source.KiwisaverEmployeeRate,
        KiwisaverEmployerContribution = source.KiwisaverEmployerContribution,
        Esct = source.Esct,
        Deductions = source.Deductions is null ? null : source.Deductions.Select(item => item is null ? null! : Copy(item)).ToList(),
        Reimbursements = source.Reimbursements,
        LeaveBalances = source.LeaveBalances is null ? null : Copy(source.LeaveBalances),
        Ytd = source.Ytd is null ? null : Copy(source.Ytd),
    };
}
