// <auto-generated> Generated from ecosystems/node/src/payslipV2.ts; do not edit. </auto-generated>
#nullable enable
using System.Text.Json.Serialization;

namespace Verifiabl.Client;

/// <summary>Generated AU/NZ v2 non-PII wire fields; the API validates values.</summary>
public sealed class AustralianPayslipV2Hourly
{
    /// <summary>Wire field <c>ordinary_rate</c>.</summary>
    [JsonPropertyName("ordinary_rate")]
    public required PayslipNumber OrdinaryRate { get; init; }

    /// <summary>Wire field <c>hours</c>.</summary>
    [JsonPropertyName("hours")]
    public required PayslipNumber Hours { get; init; }

    /// <summary>Wire field <c>amount</c>.</summary>
    [JsonPropertyName("amount")]
    public required PayslipNumber Amount { get; init; }
}

/// <summary>Generated AU/NZ v2 non-PII wire fields; the API validates values.</summary>
public sealed class AustralianPayslipV2EarningsItem
{
    /// <summary>Wire field <c>type</c>.</summary>
    [JsonPropertyName("type")]
    public required string Type { get; init; }

    /// <summary>Wire field <c>leave_type</c>.</summary>
    [JsonPropertyName("leave_type")]
    public string? LeaveType { get; init; }

    /// <summary>Wire field <c>amount</c>.</summary>
    [JsonPropertyName("amount")]
    public required PayslipNumber Amount { get; init; }

    /// <summary>Wire field <c>units</c>.</summary>
    [JsonPropertyName("units")]
    public PayslipNumber? Units { get; init; }

    /// <summary>Wire field <c>rate</c>.</summary>
    [JsonPropertyName("rate")]
    public PayslipNumber? Rate { get; init; }

    /// <summary>Wire field <c>ytd_amount</c>.</summary>
    [JsonPropertyName("ytd_amount")]
    public PayslipNumber? YtdAmount { get; init; }

    /// <summary>Wire field <c>allowance_type</c>.</summary>
    [JsonPropertyName("allowance_type")]
    public string? AllowanceType { get; init; }

    /// <summary>Wire field <c>other_category</c>.</summary>
    [JsonPropertyName("other_category")]
    public string? OtherCategory { get; init; }
}

/// <summary>Generated AU/NZ v2 non-PII wire fields; the API validates values.</summary>
public sealed class AustralianPayslipV2SalarySacrificeItem
{
    /// <summary>Wire field <c>type</c>.</summary>
    [JsonPropertyName("type")]
    public required string Type { get; init; }

    /// <summary>Wire field <c>amount</c>.</summary>
    [JsonPropertyName("amount")]
    public required PayslipNumber Amount { get; init; }

    /// <summary>Wire field <c>ytd_amount</c>.</summary>
    [JsonPropertyName("ytd_amount")]
    public PayslipNumber? YtdAmount { get; init; }
}

/// <summary>Generated AU/NZ v2 non-PII wire fields; the API validates values.</summary>
public sealed class AustralianPayslipV2DeductionsItem
{
    /// <summary>Wire field <c>type</c>.</summary>
    [JsonPropertyName("type")]
    public required string Type { get; init; }

    /// <summary>Wire field <c>amount</c>.</summary>
    [JsonPropertyName("amount")]
    public required PayslipNumber Amount { get; init; }

    /// <summary>Wire field <c>ytd_amount</c>.</summary>
    [JsonPropertyName("ytd_amount")]
    public PayslipNumber? YtdAmount { get; init; }
}

/// <summary>Generated AU/NZ v2 non-PII wire fields; the API validates values.</summary>
public sealed class AustralianPayslipV2SuperannuationItem
{
    /// <summary>Wire field <c>contribution_type</c>.</summary>
    [JsonPropertyName("contribution_type")]
    public required string ContributionType { get; init; }

    /// <summary>Wire field <c>amount</c>.</summary>
    [JsonPropertyName("amount")]
    public required PayslipNumber Amount { get; init; }

    /// <summary>Wire field <c>rate</c>.</summary>
    [JsonPropertyName("rate")]
    public PayslipNumber? Rate { get; init; }

    /// <summary>Wire field <c>ytd_amount</c>.</summary>
    [JsonPropertyName("ytd_amount")]
    public PayslipNumber? YtdAmount { get; init; }

    /// <summary>Wire field <c>usi</c>.</summary>
    [JsonPropertyName("usi")]
    public string? Usi { get; init; }
}

/// <summary>Generated AU/NZ v2 non-PII wire fields; the API validates values.</summary>
public sealed class AustralianPayslipV2Ytd
{
    /// <summary>Wire field <c>taxable</c>.</summary>
    [JsonPropertyName("taxable")]
    public PayslipNumber? Taxable { get; init; }

    /// <summary>Wire field <c>super</c>.</summary>
    [JsonPropertyName("super")]
    public PayslipNumber? Super { get; init; }

    /// <summary>Wire field <c>non_taxable</c>.</summary>
    [JsonPropertyName("non_taxable")]
    public PayslipNumber? NonTaxable { get; init; }

    /// <summary>Wire field <c>post_tax_deductions</c>.</summary>
    [JsonPropertyName("post_tax_deductions")]
    public PayslipNumber? PostTaxDeductions { get; init; }

    /// <summary>Wire field <c>reimbursements</c>.</summary>
    [JsonPropertyName("reimbursements")]
    public PayslipNumber? Reimbursements { get; init; }
}

/// <summary>Generated AU/NZ v2 non-PII wire fields; the API validates values.</summary>
public sealed class AustralianPayslipV2
{
    /// <summary>Wire field <c>period_start</c>.</summary>
    [JsonPropertyName("period_start")]
    public string? PeriodStart { get; init; }

    /// <summary>Wire field <c>period_end</c>.</summary>
    [JsonPropertyName("period_end")]
    public required string PeriodEnd { get; init; }

    /// <summary>Wire field <c>payment_date</c>.</summary>
    [JsonPropertyName("payment_date")]
    public required string PaymentDate { get; init; }

    /// <summary>Wire field <c>currency</c>.</summary>
    [JsonPropertyName("currency")]
    public string? Currency { get; init; }

    /// <summary>Wire field <c>gross</c>.</summary>
    [JsonPropertyName("gross")]
    public required PayslipNumber Gross { get; init; }

    /// <summary>Wire field <c>paygw</c>.</summary>
    [JsonPropertyName("paygw")]
    public required PayslipNumber Paygw { get; init; }

    /// <summary>Wire field <c>net</c>.</summary>
    [JsonPropertyName("net")]
    public required PayslipNumber Net { get; init; }

    /// <summary>Wire field <c>ytd_gross</c>.</summary>
    [JsonPropertyName("ytd_gross")]
    public PayslipNumber? YtdGross { get; init; }

    /// <summary>Wire field <c>ytd_paygw</c>.</summary>
    [JsonPropertyName("ytd_paygw")]
    public PayslipNumber? YtdPaygw { get; init; }

    /// <summary>Wire field <c>pay_frequency</c>.</summary>
    [JsonPropertyName("pay_frequency")]
    public string? PayFrequency { get; init; }

    /// <summary>Wire field <c>employment_basis</c>.</summary>
    [JsonPropertyName("employment_basis")]
    public string? EmploymentBasis { get; init; }

    /// <summary>Wire field <c>engagement_type</c>.</summary>
    [JsonPropertyName("engagement_type")]
    public string? EngagementType { get; init; }

    /// <summary>Wire field <c>award</c>.</summary>
    [JsonPropertyName("award")]
    public string? Award { get; init; }

    /// <summary>Wire field <c>hourly</c>.</summary>
    [JsonPropertyName("hourly")]
    public AustralianPayslipV2Hourly? Hourly { get; init; }

    /// <summary>Wire field <c>annual_rate</c>.</summary>
    [JsonPropertyName("annual_rate")]
    public PayslipNumber? AnnualRate { get; init; }

    /// <summary>Wire field <c>taxable_gross</c>.</summary>
    [JsonPropertyName("taxable_gross")]
    public PayslipNumber? TaxableGross { get; init; }

    /// <summary>Wire field <c>stsl_withholding</c>.</summary>
    [JsonPropertyName("stsl_withholding")]
    public PayslipNumber? StslWithholding { get; init; }

    /// <summary>Wire field <c>earnings</c>.</summary>
    [JsonPropertyName("earnings")]
    public IReadOnlyList<AustralianPayslipV2EarningsItem>? Earnings { get; init; }

    /// <summary>Wire field <c>salary_sacrifice</c>.</summary>
    [JsonPropertyName("salary_sacrifice")]
    public IReadOnlyList<AustralianPayslipV2SalarySacrificeItem>? SalarySacrifice { get; init; }

    /// <summary>Wire field <c>deductions</c>.</summary>
    [JsonPropertyName("deductions")]
    public IReadOnlyList<AustralianPayslipV2DeductionsItem>? Deductions { get; init; }

    /// <summary>Wire field <c>superannuation</c>.</summary>
    [JsonPropertyName("superannuation")]
    public IReadOnlyList<AustralianPayslipV2SuperannuationItem>? Superannuation { get; init; }

    /// <summary>Wire field <c>reimbursements</c>.</summary>
    [JsonPropertyName("reimbursements")]
    public PayslipNumber? Reimbursements { get; init; }

    /// <summary>Wire field <c>ytd</c>.</summary>
    [JsonPropertyName("ytd")]
    public AustralianPayslipV2Ytd? Ytd { get; init; }
}

/// <summary>Generated AU/NZ v2 non-PII wire fields; the API validates values.</summary>
public sealed class NewZealandPayslipV2Hourly
{
    /// <summary>Wire field <c>ordinary_rate</c>.</summary>
    [JsonPropertyName("ordinary_rate")]
    public required PayslipNumber OrdinaryRate { get; init; }

    /// <summary>Wire field <c>hours</c>.</summary>
    [JsonPropertyName("hours")]
    public required PayslipNumber Hours { get; init; }

    /// <summary>Wire field <c>amount</c>.</summary>
    [JsonPropertyName("amount")]
    public required PayslipNumber Amount { get; init; }
}

/// <summary>Generated AU/NZ v2 non-PII wire fields; the API validates values.</summary>
public sealed class NewZealandPayslipV2EarningsItem
{
    /// <summary>Wire field <c>type</c>.</summary>
    [JsonPropertyName("type")]
    public required string Type { get; init; }

    /// <summary>Wire field <c>leave_type</c>.</summary>
    [JsonPropertyName("leave_type")]
    public string? LeaveType { get; init; }

    /// <summary>Wire field <c>amount</c>.</summary>
    [JsonPropertyName("amount")]
    public required PayslipNumber Amount { get; init; }

    /// <summary>Wire field <c>units</c>.</summary>
    [JsonPropertyName("units")]
    public PayslipNumber? Units { get; init; }

    /// <summary>Wire field <c>rate</c>.</summary>
    [JsonPropertyName("rate")]
    public PayslipNumber? Rate { get; init; }

    /// <summary>Wire field <c>ytd_amount</c>.</summary>
    [JsonPropertyName("ytd_amount")]
    public PayslipNumber? YtdAmount { get; init; }

    /// <summary>Wire field <c>allowance_type</c>.</summary>
    [JsonPropertyName("allowance_type")]
    public string? AllowanceType { get; init; }
}

/// <summary>Generated AU/NZ v2 non-PII wire fields; the API validates values.</summary>
public sealed class NewZealandPayslipV2DeductionsItem
{
    /// <summary>Wire field <c>type</c>.</summary>
    [JsonPropertyName("type")]
    public required string Type { get; init; }

    /// <summary>Wire field <c>amount</c>.</summary>
    [JsonPropertyName("amount")]
    public required PayslipNumber Amount { get; init; }

    /// <summary>Wire field <c>ytd_amount</c>.</summary>
    [JsonPropertyName("ytd_amount")]
    public PayslipNumber? YtdAmount { get; init; }
}

/// <summary>Generated AU/NZ v2 non-PII wire fields; the API validates values.</summary>
public sealed class NewZealandPayslipV2LeaveBalancesAnnual
{
    /// <summary>Wire field <c>amount</c>.</summary>
    [JsonPropertyName("amount")]
    public required PayslipNumber Amount { get; init; }

    /// <summary>Wire field <c>unit</c>.</summary>
    [JsonPropertyName("unit")]
    public required string Unit { get; init; }
}

/// <summary>Generated AU/NZ v2 non-PII wire fields; the API validates values.</summary>
public sealed class NewZealandPayslipV2LeaveBalancesAnnualAccruedThisPeriod
{
    /// <summary>Wire field <c>amount</c>.</summary>
    [JsonPropertyName("amount")]
    public required PayslipNumber Amount { get; init; }

    /// <summary>Wire field <c>unit</c>.</summary>
    [JsonPropertyName("unit")]
    public required string Unit { get; init; }
}

/// <summary>Generated AU/NZ v2 non-PII wire fields; the API validates values.</summary>
public sealed class NewZealandPayslipV2LeaveBalancesSick
{
    /// <summary>Wire field <c>amount</c>.</summary>
    [JsonPropertyName("amount")]
    public required PayslipNumber Amount { get; init; }

    /// <summary>Wire field <c>unit</c>.</summary>
    [JsonPropertyName("unit")]
    public required string Unit { get; init; }
}

/// <summary>Generated AU/NZ v2 non-PII wire fields; the API validates values.</summary>
public sealed class NewZealandPayslipV2LeaveBalancesSickAccruedThisPeriod
{
    /// <summary>Wire field <c>amount</c>.</summary>
    [JsonPropertyName("amount")]
    public required PayslipNumber Amount { get; init; }

    /// <summary>Wire field <c>unit</c>.</summary>
    [JsonPropertyName("unit")]
    public required string Unit { get; init; }
}

/// <summary>Generated AU/NZ v2 non-PII wire fields; the API validates values.</summary>
public sealed class NewZealandPayslipV2LeaveBalancesAlternative
{
    /// <summary>Wire field <c>amount</c>.</summary>
    [JsonPropertyName("amount")]
    public required PayslipNumber Amount { get; init; }

    /// <summary>Wire field <c>unit</c>.</summary>
    [JsonPropertyName("unit")]
    public required string Unit { get; init; }
}

/// <summary>Generated AU/NZ v2 non-PII wire fields; the API validates values.</summary>
public sealed class NewZealandPayslipV2LeaveBalances
{
    /// <summary>Wire field <c>annual</c>.</summary>
    [JsonPropertyName("annual")]
    public NewZealandPayslipV2LeaveBalancesAnnual? Annual { get; init; }

    /// <summary>Wire field <c>annual_accrued_this_period</c>.</summary>
    [JsonPropertyName("annual_accrued_this_period")]
    public NewZealandPayslipV2LeaveBalancesAnnualAccruedThisPeriod? AnnualAccruedThisPeriod { get; init; }

    /// <summary>Wire field <c>sick</c>.</summary>
    [JsonPropertyName("sick")]
    public NewZealandPayslipV2LeaveBalancesSick? Sick { get; init; }

    /// <summary>Wire field <c>sick_accrued_this_period</c>.</summary>
    [JsonPropertyName("sick_accrued_this_period")]
    public NewZealandPayslipV2LeaveBalancesSickAccruedThisPeriod? SickAccruedThisPeriod { get; init; }

    /// <summary>Wire field <c>alternative</c>.</summary>
    [JsonPropertyName("alternative")]
    public NewZealandPayslipV2LeaveBalancesAlternative? Alternative { get; init; }
}

/// <summary>Generated AU/NZ v2 non-PII wire fields; the API validates values.</summary>
public sealed class NewZealandPayslipV2Ytd
{
    /// <summary>Wire field <c>student_loan</c>.</summary>
    [JsonPropertyName("student_loan")]
    public PayslipNumber? StudentLoan { get; init; }

    /// <summary>Wire field <c>kiwisaver_employee</c>.</summary>
    [JsonPropertyName("kiwisaver_employee")]
    public PayslipNumber? KiwisaverEmployee { get; init; }

    /// <summary>Wire field <c>kiwisaver_employer</c>.</summary>
    [JsonPropertyName("kiwisaver_employer")]
    public PayslipNumber? KiwisaverEmployer { get; init; }

    /// <summary>Wire field <c>child_support</c>.</summary>
    [JsonPropertyName("child_support")]
    public PayslipNumber? ChildSupport { get; init; }

    /// <summary>Wire field <c>non_taxable</c>.</summary>
    [JsonPropertyName("non_taxable")]
    public PayslipNumber? NonTaxable { get; init; }

    /// <summary>Wire field <c>post_tax_deductions</c>.</summary>
    [JsonPropertyName("post_tax_deductions")]
    public PayslipNumber? PostTaxDeductions { get; init; }

    /// <summary>Wire field <c>reimbursements</c>.</summary>
    [JsonPropertyName("reimbursements")]
    public PayslipNumber? Reimbursements { get; init; }
}

/// <summary>Generated AU/NZ v2 non-PII wire fields; the API validates values.</summary>
public sealed class NewZealandPayslipV2
{
    /// <summary>Wire field <c>period_start</c>.</summary>
    [JsonPropertyName("period_start")]
    public string? PeriodStart { get; init; }

    /// <summary>Wire field <c>period_end</c>.</summary>
    [JsonPropertyName("period_end")]
    public required string PeriodEnd { get; init; }

    /// <summary>Wire field <c>payment_date</c>.</summary>
    [JsonPropertyName("payment_date")]
    public required string PaymentDate { get; init; }

    /// <summary>Wire field <c>currency</c>.</summary>
    [JsonPropertyName("currency")]
    public string? Currency { get; init; }

    /// <summary>Wire field <c>gross</c>.</summary>
    [JsonPropertyName("gross")]
    public required PayslipNumber Gross { get; init; }

    /// <summary>Wire field <c>paye</c>.</summary>
    [JsonPropertyName("paye")]
    public required PayslipNumber Paye { get; init; }

    /// <summary>Wire field <c>net</c>.</summary>
    [JsonPropertyName("net")]
    public required PayslipNumber Net { get; init; }

    /// <summary>Wire field <c>ytd_gross</c>.</summary>
    [JsonPropertyName("ytd_gross")]
    public PayslipNumber? YtdGross { get; init; }

    /// <summary>Wire field <c>ytd_paye</c>.</summary>
    [JsonPropertyName("ytd_paye")]
    public PayslipNumber? YtdPaye { get; init; }

    /// <summary>Wire field <c>pay_cycle</c>.</summary>
    [JsonPropertyName("pay_cycle")]
    public string? PayCycle { get; init; }

    /// <summary>Wire field <c>tax_code</c>.</summary>
    [JsonPropertyName("tax_code")]
    public string? TaxCode { get; init; }

    /// <summary>Wire field <c>employment_type</c>.</summary>
    [JsonPropertyName("employment_type")]
    public string? EmploymentType { get; init; }

    /// <summary>Wire field <c>hours_paid</c>.</summary>
    [JsonPropertyName("hours_paid")]
    public PayslipNumber? HoursPaid { get; init; }

    /// <summary>Wire field <c>hourly</c>.</summary>
    [JsonPropertyName("hourly")]
    public NewZealandPayslipV2Hourly? Hourly { get; init; }

    /// <summary>Wire field <c>annual_rate</c>.</summary>
    [JsonPropertyName("annual_rate")]
    public PayslipNumber? AnnualRate { get; init; }

    /// <summary>Wire field <c>earnings_not_liable_for_acc</c>.</summary>
    [JsonPropertyName("earnings_not_liable_for_acc")]
    public PayslipNumber? EarningsNotLiableForAcc { get; init; }

    /// <summary>Wire field <c>earnings</c>.</summary>
    [JsonPropertyName("earnings")]
    public IReadOnlyList<NewZealandPayslipV2EarningsItem>? Earnings { get; init; }

    /// <summary>Wire field <c>employee_share_scheme</c>.</summary>
    [JsonPropertyName("employee_share_scheme")]
    public PayslipNumber? EmployeeShareScheme { get; init; }

    /// <summary>Wire field <c>prior_period_gross_adjustment</c>.</summary>
    [JsonPropertyName("prior_period_gross_adjustment")]
    public PayslipNumber? PriorPeriodGrossAdjustment { get; init; }

    /// <summary>Wire field <c>prior_period_paye_adjustment</c>.</summary>
    [JsonPropertyName("prior_period_paye_adjustment")]
    public PayslipNumber? PriorPeriodPayeAdjustment { get; init; }

    /// <summary>Wire field <c>payroll_donation_tax_credit</c>.</summary>
    [JsonPropertyName("payroll_donation_tax_credit")]
    public PayslipNumber? PayrollDonationTaxCredit { get; init; }

    /// <summary>Wire field <c>student_loan</c>.</summary>
    [JsonPropertyName("student_loan")]
    public PayslipNumber? StudentLoan { get; init; }

    /// <summary>Wire field <c>slcir</c>.</summary>
    [JsonPropertyName("slcir")]
    public PayslipNumber? Slcir { get; init; }

    /// <summary>Wire field <c>slbor</c>.</summary>
    [JsonPropertyName("slbor")]
    public PayslipNumber? Slbor { get; init; }

    /// <summary>Wire field <c>child_support</c>.</summary>
    [JsonPropertyName("child_support")]
    public PayslipNumber? ChildSupport { get; init; }

    /// <summary>Wire field <c>kiwisaver_employee_deduction</c>.</summary>
    [JsonPropertyName("kiwisaver_employee_deduction")]
    public PayslipNumber? KiwisaverEmployeeDeduction { get; init; }

    /// <summary>Wire field <c>kiwisaver_employee_rate</c>.</summary>
    [JsonPropertyName("kiwisaver_employee_rate")]
    public PayslipNumber? KiwisaverEmployeeRate { get; init; }

    /// <summary>Wire field <c>kiwisaver_employer_contribution</c>.</summary>
    [JsonPropertyName("kiwisaver_employer_contribution")]
    public PayslipNumber? KiwisaverEmployerContribution { get; init; }

    /// <summary>Wire field <c>esct</c>.</summary>
    [JsonPropertyName("esct")]
    public PayslipNumber? Esct { get; init; }

    /// <summary>Wire field <c>deductions</c>.</summary>
    [JsonPropertyName("deductions")]
    public IReadOnlyList<NewZealandPayslipV2DeductionsItem>? Deductions { get; init; }

    /// <summary>Wire field <c>reimbursements</c>.</summary>
    [JsonPropertyName("reimbursements")]
    public PayslipNumber? Reimbursements { get; init; }

    /// <summary>Wire field <c>leave_balances</c>.</summary>
    [JsonPropertyName("leave_balances")]
    public NewZealandPayslipV2LeaveBalances? LeaveBalances { get; init; }

    /// <summary>Wire field <c>ytd</c>.</summary>
    [JsonPropertyName("ytd")]
    public NewZealandPayslipV2Ytd? Ytd { get; init; }
}
